### ISSUE TITLE
make-texture fails

### ISSUE THREAD

**Issue by metayan** [cbaggers/play-with-verts#6]
In episode 46 & 47, after ```(play :start)```
```(make-texture nil :dimensions '(64 64) :element-type :vec3)```
in the REPL fails with
```
Attempted to register TEXTURE before id fully initialized
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [CONTINUE] Retry assertion with new value for CEPL.CONTEXT::ID.
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {10074B9B93}>)

Backtrace:
  0: (SB-KERNEL:ASSERT-ERROR (> CEPL.CONTEXT::ID 0) ((CEPL.CONTEXT::ID 0)) (CEPL.CONTEXT::ID) "Attempted to register ~s before id fully initialized" TEXTURE)
  1: (CEPL.CONTEXT::REGISTER-TEXTURE #<CEPL-CONTEXT #<THREAD "main thread" RUNNING {10006585B3}>> #<TEXTURE-2D (64x64)>)
  2: (CEPL.TEXTURES::%MAKE-TEXTURE #<TEXTURE-2D (64x64)> (64 64) NIL 1 NIL NIL NIL T NIL :RGB32F NIL T NIL NIL)
  3: (MAKE-TEXTURE NIL :DIMENSIONS (64 64) :ELEMENT-TYPE :VEC3 :MIPMAP NIL :LAYER-COUNT 1 :CUBES NIL :RECTANGLE NIL :IMMUTABLE T :BUFFER-STORAGE NIL :GENERATE-MIPMAPS T :PIXEL-FORMAT NIL :SAMPLES NIL :FIXE..
```

```(reset)``` while the rendering is running also fails with
```
Attempted to register TEXTURE before id fully initialized
   [Condition of type SIMPLE-ERROR]

Restarts:
 0: [CONTINUE] Retry assertion with new value for CEPL.CONTEXT::ID.
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1007FB9B93}>)

Backtrace:
  0: (SB-KERNEL:ASSERT-ERROR (> CEPL.CONTEXT::ID 0) ((CEPL.CONTEXT::ID 0)) (CEPL.CONTEXT::ID) "Attempted to register ~s before id fully initialized" TEXTURE)
  1: (CEPL.CONTEXT::REGISTER-TEXTURE #<CEPL-CONTEXT #<THREAD "main thread" RUNNING {10006585B3}>> #<TEXTURE-2D (600x600)>)
  2: (CEPL.TEXTURES::%MAKE-TEXTURE #<TEXTURE-2D (600x600)> (600 600) NIL 1 NIL NIL NIL T NIL :RGBA8 NIL T NIL NIL)
  3: (MAKE-TEXTURE NIL :DIMENSIONS (600 600) :ELEMENT-TYPE :RGBA8 :MIPMAP NIL :LAYER-COUNT 1 :CUBES NIL :RECTANGLE NIL :IMMUTABLE T :BUFFER-STORAGE NIL :GENERATE-MIPMAPS T :PIXEL-FORMAT NIL :SAMPLES NIL :F..
  4: (CEPL.FBOS::%GEN-TEXTURE 0)
  5: (CEPL.FBOS::PROCESS-FBO-INIT-PATTERN (0 :D))
  6: (CEPL.FBOS::FBO-GEN-ATTACH #<FBO :UNINITIALIZED> T 0 :D)
  7: (MAKE-FBO 0 :D)
  8: (RESET)
```
and also triggers
```
OpenGL signalled (1282 . INVALID-OPERATION) from DRAW-BUFFERS.
   [Condition of type CL-OPENGL-BINDINGS:OPENGL-ERROR]

Restarts:
 0: [CONTINUE] Continue
 1: [CONTINUE] Livesupport: Continue
 2: [ABORT] Exit debugger, returning to top level.

Backtrace:
  0: (CL-OPENGL-BINDINGS:CHECK-ERROR #<unavailable argument>)
  1: (CL-OPENGL-BINDINGS:DRAW-BUFFERS 1 #.(SB-SYS:INT-SAP #X00277B70))
  2: (PLAY-WITH-VERTS::GAME-STEP)
  3: (PLAY-WITH-VERTS::%PLAY-STEP-FUNC*)
  4: (PLAY-WITH-VERTS::PLAY :START NIL)
```

**Comment by cbaggers** [comment]
This hasnt been forgotten :)

This is a braindump as I work through this

From the backtrace..
```
Backtrace:
  0: (SB-KERNEL:ASSERT-ERROR (> CEPL.CONTEXT::ID 0) ((CEPL.CONTEXT::ID 0)) (CEPL.CONTEXT::ID) "Attempted to register ~s before id fully initialized" TEXTURE)
  1: (CEPL.CONTEXT::REGISTER-TEXTURE #<CEPL-CONTEXT #<THREAD "main thread" RUNNING {10006585B3}>> 
```
.. We can see that the `ID` was 0 which is a problem as that is a reserved ID. In `%make-texture` we can see that the call to [gen-texture](https://github.com/cbaggers/cepl/blob/master/core/textures/textures.lisp#L588) definitely comes before the call to [register-texture](https://github.com/cbaggers/cepl/blob/master/core/textures/textures.lisp#L600) so the clue to the issue must be in `gen-texture`

```
(defun+ gen-texture ()
  (first (gl:gen-textures 1)))
```
Hmm not much here, so it would have to be in the cl-opengl lib (very unlikely) or something I've misunderstood with [glGenTextures](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGenTextures.xhtml). not loads of info but as [glIsTexture](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glIsTexture.xhtml)  hints the 0 value is not valid.

So we jump back to the wiki entry for [GL Objects](https://www.khronos.org/opengl/wiki/OpenGL_Object#Object_Creation_and_Destruction)

> An object name is always a GLuint. These names are not pointers, nor should you assume that they are. They are references, numbers that identify an object. They can be any 32-bit unsigned integer except 0. The object number 0 is reserved for special use cases; see below for details.

So at last to the [object zero](https://www.khronos.org/opengl/wiki/OpenGL_Object#Object_zero) entry

> For some objects, object 0 represents a kind of "default object". Textures have a default texture. However, the default texture is very complex to use; texture object 0 technically represents multiple default textures. Furthermore, default textures cannot be used in many ways that regular texture objects can. For example, you cannot attach images of them to FBOs. Therefore, you are strongly encouraged to think of texture 0 as a non-existent texture.

huh, well I didnt know that, but I dont think it changes much. I'm going to check the spec.

GLSpec4.4 - 8.1 says:

> 8.1    Texture Objects
> Textures  in  GL  are  represented  by  named  objects.    The  name  space  for  texture objects is the unsigned integers,  with zero reserved by the GL to represent the  default  texture  object.

Yup so 0 is definitely reserved.

So the only way I think that could be given out as an id is if GL wasnt initialized properly first. 

It's a bit odd though as CEPL has some logic for things being created before the gl context is ready, so it should have used that..so it believes the gl context is available.. hmm.. what about a threading issue?

Could you try the following please:
- Run `(play :start)` like normal (you should now have a gl window)
- Run `(list (bt:current-thread) (cepl:cepl-context) (cepl.context::%cepl-context-bound-thread (cepl:cepl-context)))` and paste the result in a response below, it should look something like:

```
CL-USER> (list (bt:current-thread) (cepl:cepl-context) (cepl.context::%cepl-context-bound-thread (cepl:cepl-context)))
(#<SB-THREAD:THREAD "repl-thread" RUNNING {1003558033}>
 #<CEPL-CONTEXT #<THREAD "repl-thread" RUNNING {1003558033}>>
 #<SB-THREAD:THREAD "repl-thread" RUNNING {1003558033}>)
```

Thanks @metayan I wonder what this will end up being

**Comment by metayan** [comment]
I get
```
(#<SB-THREAD:THREAD "repl-thread" RUNNING {1006A31B93}>
 #<CEPL-CONTEXT #<THREAD "main thread" RUNNING {10006705B3}>>
 #<SB-THREAD:THREAD "main thread" RUNNING {10006705B3}>)
```
which I suppose explains why the errors show up.

The errors appear if `(play :start)` is run from the SBCL prompt and then using `slime-connect` from Emacs to connect to the SBCL instance. I was trying this, because it is the only way that I've managed to get keyboard/mouse/gamepad input to work in a GL window with CEPL on OSX. When I've started SBCL from Emacs, the errors don't appear, but then I haven't been able to control anything "live" in the GL window.
Is there some way to get keyboard/mouse/gamepad input to work in a GL window even when SBCL is started from Emacs?
